// VERIFIQ — Report Templates
// Copyright 2026 BBMW0 Technologies. Developed by Jia Wen Gan.
//
// Professional report templates. Each template defines a visual identity,
// section layout, and metadata for all export formats (Word, PDF/HTML, Excel, etc.).
//
// Templates:
//   Professional (default) — Full branded VERIFIQ layout
//   Executive Summary      — One-page concise overview for C-suite / clients
//   BCA-Format             — Singapore BCA Building Control submission style
//   SCDF-Format            — Singapore SCDF Fire Safety report style
//   NBeS-Format            — Malaysia NBeS / UBBL submission style
//   Minimal                — Clean, unbranded, print-optimised
//   Technical              — Dense, data-rich, engineering audience
//   Audit Trail            — Chronological event log format for auditors

using VERIFIQ.Core.Enums;

namespace VERIFIQ.Reports;

public enum ReportTemplate
{
    Professional    = 1,   // Default: full VERIFIQ brand, all sections
    ExecutiveSummary = 2,  // One-page overview, KPIs, no detailed findings list
    BcaFormat       = 3,   // Singapore BCA Building Control format
    ScdfFormat      = 4,   // Singapore SCDF Fire Safety submission format
    NbesFormat      = 5,   // Malaysia NBeS / UBBL format
    Minimal         = 6,   // Clean, unbranded, print-first
    Technical       = 7,   // Dense, engineering data, all fields shown
    AuditTrail      = 8,   // Chronological log for audit/compliance review
}

public sealed class TemplateDefinition
{
    public ReportTemplate Id             { get; init; }
    public string         Name           { get; init; } = string.Empty;
    public string         Description    { get; init; } = string.Empty;
    public string         BadgeLabel     { get; init; } = string.Empty;
    public string         BadgeColour    { get; init; } = "#0E7C86";
    public string         PrimaryColour  { get; init; } = "#0B1F45";
    public string         AccentColour   { get; init; } = "#0E7C86";
    public string         FontFamily     { get; init; } = "Arial, Helvetica, sans-serif";
    public bool           ShowLogo       { get; init; } = true;
    public bool           ShowFindings   { get; init; } = true;
    public bool           ShowDesignCode { get; init; } = true;
    public bool           ShowFormulas   { get; init; } = true;
    public bool           ShowAgencyBreakdown { get; init; } = true;
    public bool           ShowElementSchedule { get; init; } = false;
    public bool           CompactMode    { get; init; } = false;
    public int            MaxFindings    { get; init; } = 500;
    public CountryMode    TargetCountry  { get; init; } = CountryMode.Combined;
    public string         FooterText     { get; init; } = "Generated by VERIFIQ IFC Compliance Checker | BBMW0 Technologies | Developed by Jia Wen Gan";
    public string         PrintMargin    { get; init; } = "20mm 18mm";  // CSS @page margin
}

public static class ReportTemplates
{
    public static readonly IReadOnlyList<TemplateDefinition> All = new[]
    {
        new TemplateDefinition
        {
            Id           = ReportTemplate.Professional,
            Name         = "Professional",
            Description  = "Full branded VERIFIQ layout with all sections, agency breakdown, design code findings, and detailed remediation guidance.",
            BadgeLabel   = "Default",
            BadgeColour  = "#0E7C86",
            PrimaryColour = "#0B1F45",
            AccentColour  = "#0E7C86",
            ShowLogo     = true,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = true,
            ShowAgencyBreakdown = true,
            MaxFindings  = 500,
            FooterText   = "Generated by VERIFIQ IFC Compliance Checker | BBMW0 Technologies | Developed by Jia Wen Gan",
            PrintMargin  = "20mm 18mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.ExecutiveSummary,
            Name         = "Executive Summary",
            Description  = "One-page concise overview for clients and C-suite: compliance scores, KPIs, agency summary, and top critical issues. No detailed findings list.",
            BadgeLabel   = "Concise",
            BadgeColour  = "#1D4ED8",
            PrimaryColour = "#0B1F45",
            AccentColour  = "#1D4ED8",
            ShowLogo     = true,
            ShowFindings = false,
            ShowDesignCode = true,
            ShowFormulas = true,
            ShowAgencyBreakdown = true,
            CompactMode  = true,
            MaxFindings  = 10,  // Top 10 critical issues only
            FooterText   = "VERIFIQ IFC Compliance Checker | Executive Summary | BBMW0 Technologies",
            PrintMargin  = "22mm 20mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.BcaFormat,
            Name         = "BCA Format",
            Description  = "Singapore Building and Construction Authority submission style. Dark blue header, BCA agency sections prominent, accessibility and structural checks emphasised.",
            BadgeLabel   = "Singapore",
            BadgeColour  = "#1D4ED8",
            PrimaryColour = "#003087",  // BCA deep blue
            AccentColour  = "#E8B400",  // BCA gold
            FontFamily   = "Arial, Helvetica, sans-serif",
            ShowLogo     = true,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = true,
            ShowAgencyBreakdown = true,
            TargetCountry = CountryMode.Singapore,
            MaxFindings  = 500,
            FooterText   = "VERIFIQ IFC Compliance Checker | Singapore CORENET-X / IFC+SG | BBMW0 Technologies",
            PrintMargin  = "25mm 20mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.ScdfFormat,
            Name         = "SCDF Format",
            Description  = "Singapore Civil Defence Force fire safety report style. Red accent, fire compartmentation and escape route findings prioritised, SCDF code references prominent.",
            BadgeLabel   = "Fire Safety",
            BadgeColour  = "#B91C1C",
            PrimaryColour = "#7F1D1D",  // SCDF deep red
            AccentColour  = "#DC2626",
            FontFamily   = "Arial, Helvetica, sans-serif",
            ShowLogo     = true,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = false,
            ShowAgencyBreakdown = true,
            TargetCountry = CountryMode.Singapore,
            MaxFindings  = 500,
            FooterText   = "VERIFIQ IFC Compliance Checker | SCDF Fire Safety Review | BBMW0 Technologies",
            PrintMargin  = "22mm 18mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.NbesFormat,
            Name         = "NBeS Format",
            Description  = "Malaysia NBeS / UBBL submission style. Deep red Malaysian accent, UBBL by-law references prominent, purpose group and fire safety sections emphasised.",
            BadgeLabel   = "Malaysia",
            BadgeColour  = "#9B1C1C",
            PrimaryColour = "#7F1D1D",  // Malaysian deep red
            AccentColour  = "#FACC15",  // Malaysian gold
            FontFamily   = "Arial, Helvetica, sans-serif",
            ShowLogo     = true,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = true,
            ShowAgencyBreakdown = true,
            TargetCountry = CountryMode.Malaysia,
            MaxFindings  = 500,
            FooterText   = "VERIFIQ IFC Compliance Checker | Malaysia NBeS / UBBL 1984 | BBMW0 Technologies",
            PrintMargin  = "25mm 20mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.Minimal,
            Name         = "Minimal",
            Description  = "Clean, unbranded, print-optimised. Black and white with minimal colour. Suitable for formal document submission or printing on office printers.",
            BadgeLabel   = "Print",
            BadgeColour  = "#374151",
            PrimaryColour = "#111827",
            AccentColour  = "#374151",
            FontFamily   = "'Times New Roman', Georgia, serif",
            ShowLogo     = false,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = true,
            ShowAgencyBreakdown = false,
            MaxFindings  = 500,
            FooterText   = "VERIFIQ IFC Compliance Report",
            PrintMargin  = "25mm 25mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.Technical,
            Name         = "Technical",
            Description  = "Dense, data-rich format for engineering teams. All fields visible, element GUIDs shown in full, all check levels displayed, element schedule included.",
            BadgeLabel   = "Engineering",
            BadgeColour  = "#374151",
            PrimaryColour = "#1F2937",
            AccentColour  = "#0891B2",
            FontFamily   = "'Segoe UI', Arial, sans-serif",
            ShowLogo     = true,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = true,
            ShowAgencyBreakdown = true,
            ShowElementSchedule = true,
            MaxFindings  = 1000,
            FooterText   = "VERIFIQ IFC Compliance Checker — Technical Report | BBMW0 Technologies",
            PrintMargin  = "15mm 12mm",
        },
        new TemplateDefinition
        {
            Id           = ReportTemplate.AuditTrail,
            Name         = "Audit Trail",
            Description  = "Chronological event log for auditors and QA teams. Ordered by element, then check level. Session metadata, file hash, and version information included.",
            BadgeLabel   = "QA / Audit",
            BadgeColour  = "#065F46",
            PrimaryColour = "#064E3B",
            AccentColour  = "#10B981",
            FontFamily   = "'Cascadia Code','Consolas','Courier New',monospace",
            ShowLogo     = false,
            ShowFindings = true,
            ShowDesignCode = true,
            ShowFormulas = false,
            ShowAgencyBreakdown = false,
            ShowElementSchedule = true,
            MaxFindings  = 1000,
            FooterText   = "VERIFIQ IFC Compliance Checker — Audit Trail",
            PrintMargin  = "18mm 15mm",
        },
    };

    public static TemplateDefinition Get(ReportTemplate template) =>
        All.FirstOrDefault(t => t.Id == template) ?? All[0];

    public static TemplateDefinition GetDefault() => All[0];
}
