// VERIFIQ - IFC Compliance Checker
// Copyright 2026 BBMW0 Technologies. Developed by Jia Wen Gan.
// Specialist report builders: Word (OpenXML), PDF (PdfSharpCore), Excel (ClosedXML)

using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using ClosedXML.Excel;
using VERIFIQ.Core.Enums;
using VERIFIQ.Core.Models;

namespace VERIFIQ.Reports;

// ─── WORD REPORT BUILDER ─────────────────────────────────────────────────────

public sealed class WordReportBuilderV1
{
    private readonly ValidationSession _session;
    private readonly string _appName;
    private readonly string _company;
    private readonly string _founder;

    public WordReportBuilderV1(ValidationSession session,
        string appName, string company, string founder)
    {
        _session = session;
        _appName = appName;
        _company = company;
        _founder = founder;
    }

    public async Task BuildAsync(string path, CancellationToken ct)
    {
        await Task.Run(() =>
        {
            using var doc = WordprocessingDocument.Create(path,
                WordprocessingDocumentType.Document);

            var mainPart = doc.AddMainDocumentPart();
            mainPart.Document = new Document();
            var body = new Body();

            // ── Title ──────────────────────────────────────────────────────
            body.AppendChild(CreateHeading1("VERIFIQ: IFC Compliance Report"));
            body.AppendChild(CreateParagraph($"{_appName}  |  {_company}"));
            body.AppendChild(CreateParagraph($"Developed by {_founder}  |  bbmw0.com"));
            body.AppendChild(CreateParagraph(
                $"Generated: {_session.StartedAt:dd MMMM yyyy HH:mm} UTC  |  " +
                $"Country: {_session.CountryMode}  |  " +
                $"Compliance Score: {_session.ComplianceScore:F1}%"));

            // ── Executive Summary ──────────────────────────────────────────
            body.AppendChild(CreateHeading2("Executive Summary"));
            body.AppendChild(CreateSummaryTable());

            // ── Errors by Agency (Singapore) ──────────────────────────────
            if (_session.CountryMode is CountryMode.Singapore or CountryMode.Combined)
            {
                body.AppendChild(CreateHeading2("Singapore  -  Errors by Agency"));
                body.AppendChild(CreateAgencyTable());
            }

            // ── Critical Issues ────────────────────────────────────────────
            body.AppendChild(CreateHeading2("Critical Issues"));
            var criticals = _session.Results
                .Where(r => r.Severity == Severity.Critical).Take(50).ToList();

            if (criticals.Count == 0)
                body.AppendChild(CreateParagraph("No critical issues found."));
            else
                body.AppendChild(CreateFindingsTable(criticals));

            // ── All Findings ───────────────────────────────────────────────
            body.AppendChild(CreateHeading2("All Compliance Findings"));
            body.AppendChild(CreateFindingsTable(
                _session.Results.OrderByDescending(r => r.Severity).ToList()));

            // ── Footer ──────────────────────────────────────────────────────
            body.AppendChild(CreateParagraph(
                $"Report generated by {_appName} | {_company} | Developed by {_founder}"));

            mainPart.Document.Body = body;
            mainPart.Document.Save();
        }, ct);
    }

    private static Paragraph CreateHeading1(string text)
    {
        return new Paragraph(
            new ParagraphProperties(new ParagraphStyleId { Val = "Heading1" }),
            new Run(new Text(text)));
    }

    private static Paragraph CreateHeading2(string text)
    {
        return new Paragraph(
            new ParagraphProperties(new ParagraphStyleId { Val = "Heading2" }),
            new Run(new Text(text)));
    }

    private static Paragraph CreateParagraph(string text, bool bold = false)
    {
        var run = new Run(new Text(text));
        if (bold) run.PrependChild(new RunProperties(new Bold()));
        return new Paragraph(run);
    }

    private Table CreateSummaryTable()
    {
        var rows = new[]
        {
            ("Total Elements",   _session.TotalElements.ToString("N0")),
            ("Fully Compliant",  _session.PassedElements.ToString("N0")),
            ("Warnings",         _session.WarningElements.ToString("N0")),
            ("Errors",           _session.ErrorElements.ToString("N0")),
            ("Critical",         _session.CriticalElements.ToString("N0")),
            ("Proxy Elements",   _session.ProxyElements.ToString("N0")),
            ("Compliance Score", $"{_session.ComplianceScore:F1}%"),
        };

        var table = new Table();
        AddTableBorders(table);

        // Header
        var headerRow = new TableRow();
        headerRow.AppendChild(MakeHeaderCell("Metric", 4500));
        headerRow.AppendChild(MakeHeaderCell("Value", 4500));
        table.AppendChild(headerRow);

        foreach (var (label, value) in rows)
        {
            var row = new TableRow();
            row.AppendChild(MakeDataCell(label, 4500));
            row.AppendChild(MakeDataCell(value, 4500));
            table.AppendChild(row);
        }
        return table;
    }

    private Table CreateAgencyTable()
    {
        var table = new Table();
        AddTableBorders(table);

        var headerRow = new TableRow();
        headerRow.AppendChild(MakeHeaderCell("Agency", 3600));
        headerRow.AppendChild(MakeHeaderCell("Error Count", 5400));
        table.AppendChild(headerRow);

        foreach (var kvp in _session.ErrorsByAgency.OrderByDescending(k => k.Value))
        {
            var row = new TableRow();
            row.AppendChild(MakeDataCell(kvp.Key.ToString(), 3600));
            row.AppendChild(MakeDataCell(kvp.Value.ToString(), 5400));
            table.AppendChild(row);
        }
        return table;
    }

    private static Table CreateFindingsTable(List<ValidationResult> results)
    {
        var table = new Table();
        AddTableBorders(table);

        var headerRow = new TableRow();
        headerRow.AppendChild(MakeHeaderCell("Severity",  1200));
        headerRow.AppendChild(MakeHeaderCell("Check Level", 1800));
        headerRow.AppendChild(MakeHeaderCell("Element",   2000));
        headerRow.AppendChild(MakeHeaderCell("GUID",      2400));
        headerRow.AppendChild(MakeHeaderCell("Agency",    900));
        headerRow.AppendChild(MakeHeaderCell("Property",  1800));
        headerRow.AppendChild(MakeHeaderCell("Issue",     3200));
        table.AppendChild(headerRow);

        foreach (var r in results.Take(2000))
        {
            var row = new TableRow();
            row.AppendChild(MakeDataCell(r.Severity.ToString(), 1200));
            row.AppendChild(MakeDataCell(r.CheckLevel.ToString(), 1800));
            row.AppendChild(MakeDataCell($"{r.ElementName}\n{r.IfcClass}", 2000));
            row.AppendChild(MakeDataCell(r.ElementGuid, 2400));
            row.AppendChild(MakeDataCell(r.AffectedAgency.ToString(), 900));
            row.AppendChild(MakeDataCell($"{r.PropertySetName}.{r.PropertyName}", 1800));
            row.AppendChild(MakeDataCell(r.Message, 3200));
            table.AppendChild(row);
        }

        return table;
    }

    private static void AddTableBorders(Table table)
    {
        var props = new TableProperties(new TableBorders(
            new TopBorder    { Val = BorderValues.Single, Size = 4, Color = "CCCCCC" },
            new BottomBorder { Val = BorderValues.Single, Size = 4, Color = "CCCCCC" },
            new LeftBorder   { Val = BorderValues.Single, Size = 4, Color = "CCCCCC" },
            new RightBorder  { Val = BorderValues.Single, Size = 4, Color = "CCCCCC" },
            new InsideHorizontalBorder { Val = BorderValues.Single, Size = 4, Color = "CCCCCC" },
            new InsideVerticalBorder   { Val = BorderValues.Single, Size = 4, Color = "CCCCCC" }
        ));
        table.PrependChild(props);
    }

    private static TableCell MakeHeaderCell(string text, int width)
    {
        var cell = new TableCell(
            new TableCellProperties(
                new TableCellWidth { Type = TableWidthUnitValues.Dxa, Width = width.ToString() },
                new Shading { Fill = "0B1F45", Val = ShadingPatternValues.Clear }
            ),
            new Paragraph(new Run(
                new RunProperties(new Bold(), new Color { Val = "FFFFFF" }),
                new Text(text)))
        );
        return cell;
    }

    private static TableCell MakeDataCell(string text, int width)
    {
        var cell = new TableCell(
            new TableCellProperties(
                new TableCellWidth { Type = TableWidthUnitValues.Dxa, Width = width.ToString() }
            ),
            new Paragraph(new Run(new Text(text)))
        );
        return cell;
    }
}

// ─── EXCEL REPORT BUILDER ────────────────────────────────────────────────────

public sealed class ExcelReportBuilderV1
{
    private readonly ValidationSession _session;
    private readonly string _appName;
    private readonly string _company;
    private readonly string _founder;

    public ExcelReportBuilderV1(ValidationSession session,
        string appName, string company, string founder)
    {
        _session = session;
        _appName = appName;
        _company = company;
        _founder = founder;
    }

    public async Task BuildAsync(string path, CancellationToken ct)
    {
        await Task.Run(() =>
        {
            using var wb = new XLWorkbook();

            // ── Sheet 1: Summary ───────────────────────────────────────────
            var wsSummary = wb.Worksheets.Add("Summary");
            StyleSummarySheet(wsSummary);

            // ── Sheet 2: All Findings ──────────────────────────────────────
            var wsFindings = wb.Worksheets.Add("All Findings");
            BuildFindingsSheet(wsFindings, _session.Results);

            // ── Sheet 3: Critical Only ─────────────────────────────────────
            var wsCrit = wb.Worksheets.Add("Critical");
            BuildFindingsSheet(wsCrit,
                _session.Results.Where(r => r.Severity == Severity.Critical).ToList());

            // ── Sheet 4: Errors Only ───────────────────────────────────────
            var wsErrors = wb.Worksheets.Add("Errors");
            BuildFindingsSheet(wsErrors,
                _session.Results.Where(r => r.Severity == Severity.Error).ToList());

            // ── Sheet 5: By Agency (SG) ────────────────────────────────────
            if (_session.CountryMode is CountryMode.Singapore or CountryMode.Combined)
            {
                var wsAgency = wb.Worksheets.Add("By Agency (SG)");
                BuildAgencySheet(wsAgency);
            }

            // ── Sheet 6: Elements ─────────────────────────────────────────
            var wsElements = wb.Worksheets.Add("Elements");
            BuildElementsSheet(wsElements);

            wb.SaveAs(path);
        }, ct);
    }

    private void StyleSummarySheet(IXLWorksheet ws)
    {
        ws.Column(1).Width = 30;
        ws.Column(2).Width = 20;

        // Title
        ws.Cell(1, 1).Value = "VERIFIQ: IFC Compliance Report";
        ws.Cell(1, 1).Style.Font.Bold = true;
        ws.Cell(1, 1).Style.Font.FontSize = 18;
        ws.Cell(1, 1).Style.Font.FontColor = XLColor.FromHtml("#0B1F45");

        ws.Cell(2, 1).Value = $"{_appName} | {_company}";
        ws.Cell(3, 1).Value = $"Developed by {_founder}";
        ws.Cell(4, 1).Value = $"Generated: {_session.StartedAt:dd MMMM yyyy HH:mm} UTC";
        ws.Cell(5, 1).Value = $"Country Mode: {_session.CountryMode}";
        ws.Cell(6, 1).Value = $"Session ID: {_session.SessionId}";

        // Summary data
        var data = new[]
        {
            ("Total Elements",  _session.TotalElements.ToString()),
            ("Fully Compliant", _session.PassedElements.ToString()),
            ("Warnings",        _session.WarningElements.ToString()),
            ("Errors",          _session.ErrorElements.ToString()),
            ("Critical",        _session.CriticalElements.ToString()),
            ("Proxy Elements",  _session.ProxyElements.ToString()),
            ("Compliance Score",$"{_session.ComplianceScore:F1}%"),
        };

        int row = 8;
        // Header
        ws.Cell(row, 1).Value = "Metric";
        ws.Cell(row, 2).Value = "Value";
        ws.Row(row).Style.Font.Bold = true;
        ws.Row(row).Style.Fill.BackgroundColor = XLColor.FromHtml("#0B1F45");
        ws.Row(row).Style.Font.FontColor = XLColor.White;
        row++;

        foreach (var (label, value) in data)
        {
            ws.Cell(row, 1).Value = label;
            ws.Cell(row, 2).Value = value;
            if (row % 2 == 0)
                ws.Row(row).Style.Fill.BackgroundColor = XLColor.FromHtml("#F4F6FA");
            row++;
        }

        // Agency breakdown
        if (_session.ErrorsByAgency.Any())
        {
            row += 2;
            ws.Cell(row, 1).Value = "Errors by Singapore Agency";
            ws.Cell(row, 1).Style.Font.Bold = true;
            ws.Cell(row, 1).Style.Font.FontSize = 14;
            row++;
            ws.Cell(row, 1).Value = "Agency";
            ws.Cell(row, 2).Value = "Error Count";
            ws.Row(row).Style.Font.Bold = true;
            ws.Row(row).Style.Fill.BackgroundColor = XLColor.FromHtml("#0B1F45");
            ws.Row(row).Style.Font.FontColor = XLColor.White;
            row++;
            foreach (var kvp in _session.ErrorsByAgency.OrderByDescending(k => k.Value))
            {
                ws.Cell(row, 1).Value = kvp.Key.ToString();
                ws.Cell(row, 2).Value = kvp.Value;
                row++;
            }
        }
    }

    private static void BuildFindingsSheet(IXLWorksheet ws, List<ValidationResult> results)
    {
        // Headers
        string[] headers =
        {
            "Severity","Check Level","Element GUID","Element Name","IFC Class",
            "Storey","Country","Agency","Gateway","Property Set","Property",
            "Expected Value","Actual Value","Message","Remediation","Rule Source"
        };

        ws.Row(1).Style.Font.Bold = true;
        ws.Row(1).Style.Fill.BackgroundColor = XLColor.FromHtml("#0B1F45");
        ws.Row(1).Style.Font.FontColor = XLColor.White;

        for (int i = 0; i < headers.Length; i++)
            ws.Cell(1, i + 1).Value = headers[i];

        // Set column widths
        ws.Column(1).Width = 12;
        ws.Column(2).Width = 25;
        ws.Column(3).Width = 36;
        ws.Column(4).Width = 30;
        ws.Column(5).Width = 28;
        ws.Column(6).Width = 20;
        ws.Column(7).Width = 15;
        ws.Column(8).Width = 10;
        ws.Column(9).Width = 18;
        ws.Column(10).Width = 25;
        ws.Column(11).Width = 30;
        ws.Column(12).Width = 30;
        ws.Column(13).Width = 30;
        ws.Column(14).Width = 60;
        ws.Column(15).Width = 60;
        ws.Column(16).Width = 40;

        int row = 2;
        foreach (var r in results)
        {
            ws.Cell(row, 1).Value  = r.Severity.ToString();
            ws.Cell(row, 2).Value  = r.CheckLevel.ToString();
            ws.Cell(row, 3).Value  = r.ElementGuid;
            ws.Cell(row, 4).Value  = r.ElementName;
            ws.Cell(row, 5).Value  = r.IfcClass;
            ws.Cell(row, 6).Value  = r.StoreyName;
            ws.Cell(row, 7).Value  = r.Country.ToString();
            ws.Cell(row, 8).Value  = r.AffectedAgency.ToString();
            ws.Cell(row, 9).Value  = r.AffectedGateway.ToString();
            ws.Cell(row, 10).Value = r.PropertySetName;
            ws.Cell(row, 11).Value = r.PropertyName;
            ws.Cell(row, 12).Value = r.ExpectedValue;
            ws.Cell(row, 13).Value = r.ActualValue;
            ws.Cell(row, 14).Value = r.Message;
            ws.Cell(row, 15).Value = r.RemediationGuidance;
            ws.Cell(row, 16).Value = r.RuleSource;

            // Colour code by severity
            var bgColour = r.Severity switch
            {
                Severity.Critical => XLColor.FromHtml("#FEF2F2"),
                Severity.Error    => XLColor.FromHtml("#FFFBEB"),
                Severity.Warning  => XLColor.FromHtml("#FFFBEB"),
                Severity.Pass     => XLColor.FromHtml("#F0FDF4"),
                _                 => XLColor.White
            };
            ws.Row(row).Style.Fill.BackgroundColor = bgColour;

            row++;
        }

        // Freeze header row and add auto-filter
        ws.SheetView.FreezeRows(1);
        ws.RangeUsed().SetAutoFilter();
    }

    private void BuildAgencySheet(IXLWorksheet ws)
    {
        ws.Row(1).Style.Font.Bold = true;
        ws.Row(1).Style.Fill.BackgroundColor = XLColor.FromHtml("#0B1F45");
        ws.Row(1).Style.Font.FontColor = XLColor.White;
        ws.Cell(1, 1).Value = "Agency";
        ws.Cell(1, 2).Value = "Error Count";
        ws.Cell(1, 3).Value = "Most Common Check Level";

        int row = 2;
        foreach (var kvp in _session.ErrorsByAgency.OrderByDescending(k => k.Value))
        {
            ws.Cell(row, 1).Value = kvp.Key.ToString();
            ws.Cell(row, 2).Value = kvp.Value;

            var mostCommon = _session.Results
                .Where(r => r.AffectedAgency == kvp.Key && r.Severity >= Severity.Error)
                .GroupBy(r => r.CheckLevel)
                .OrderByDescending(g => g.Count())
                .FirstOrDefault()?.Key.ToString() ?? "";
            ws.Cell(row, 3).Value = mostCommon;
            row++;
        }
        ws.Column(1).Width = 20;
        ws.Column(2).Width = 15;
        ws.Column(3).Width = 35;
    }

    private void BuildElementsSheet(IXLWorksheet ws)
    {
        ws.Row(1).Style.Font.Bold = true;
        ws.Row(1).Style.Fill.BackgroundColor = XLColor.FromHtml("#0B1F45");
        ws.Row(1).Style.Font.FontColor = XLColor.White;

        string[] headers =
        {
            "GUID","Element Name","IFC Class","Storey","Overall Severity",
            "Error Count","Warning Count","Is Proxy"
        };
        for (int i = 0; i < headers.Length; i++)
            ws.Cell(1, i + 1).Value = headers[i];

        int row = 2;
        foreach (var file in _session.LoadedFiles)
        {
            foreach (var element in file.Elements)
            {
                ws.Cell(row, 1).Value = element.GlobalId;
                ws.Cell(row, 2).Value = element.Name;
                ws.Cell(row, 3).Value = element.IfcClass;
                ws.Cell(row, 4).Value = element.StoreyName;
                ws.Cell(row, 5).Value = element.OverallSeverity.ToString();
                ws.Cell(row, 6).Value = element.ErrorCount;
                ws.Cell(row, 7).Value = element.WarningCount;
                ws.Cell(row, 8).Value = element.IsProxy;

                if (element.IsProxy)
                    ws.Row(row).Style.Fill.BackgroundColor = XLColor.FromHtml("#FEF2F2");

                row++;
            }
        }

        ws.Column(1).Width = 36;
        ws.Column(2).Width = 30;
        ws.Column(3).Width = 28;
        ws.Column(4).Width = 20;
        ws.Column(5).Width = 18;
        ws.Column(6).Width = 14;
        ws.Column(7).Width = 16;
        ws.Column(8).Width = 12;
        ws.SheetView.FreezeRows(1);
        ws.RangeUsed().SetAutoFilter();
    }
}

// ─── PDF REPORT BUILDER ──────────────────────────────────────────────────────

public sealed class PdfReportBuilderV1
{
    private readonly ValidationSession _session;
    private readonly string _appName;
    private readonly string _company;
    private readonly string _founder;

    private readonly ReportTemplate _template;

    public PdfReportBuilderV1(ValidationSession session,
        string appName, string company, string founder,
        ReportTemplate template = ReportTemplate.Professional)
    {
        _session  = session;
        _appName  = appName;
        _company  = company;
        _founder  = founder;
        _template = template;
    }

    public async Task BuildAsync(string path, CancellationToken ct)
    {
        // v1.0: Generate a fully printable, self-contained HTML report and save it
        // alongside the other exports. The file is named with .html extension so
        // the browser opens it directly. The user can then print → Save as PDF.
        // Native PDF generation (no browser required) is planned for v1.1.

        await Task.Run(() =>
        {
            var dc    = _session.DesignCode;
            var score = _session.ComplianceScore;
            var dScore = dc?.DesignComplianceScore ?? 100.0;
            var oScore = dc == null ? score : (score + dScore) / 2.0;

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("<!DOCTYPE html><html lang=\"en\">");
            sb.AppendLine("<head><meta charset=\"UTF-8\">");
            sb.AppendLine("<title>VERIFIQ Compliance Report</title>");
            var tmpl = ReportTemplates.Get(_template);
            sb.AppendLine("<style>");
            sb.AppendLine($"@page {{ margin: {tmpl.PrintMargin}; }}");
            sb.AppendLine("@media print { .no-print{display:none!important} body{font-size:9px} }");
            sb.AppendLine("*{box-sizing:border-box}");
            sb.AppendLine($"body{{font-family:{tmpl.FontFamily};font-size:11px;color:#1e293b;margin:0;padding:24px}}");
            sb.AppendLine($".header{{background:{tmpl.PrimaryColour};color:#fff;padding:20px 24px;border-radius:8px;margin-bottom:20px;display:flex;justify-content:space-between;align-items:flex-end}}");
            sb.AppendLine(".header-title{font-size:24px;font-weight:700;letter-spacing:-0.5px}");
            sb.AppendLine(".header-sub{font-size:12px;opacity:.75;margin-top:3px}");
            sb.AppendLine(".header-meta{text-align:right;font-size:11px;opacity:.8}");
            sb.AppendLine(".score-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:12px;margin-bottom:20px}");
            sb.AppendLine(".score-card{border:1px solid #e2e8f0;border-radius:8px;padding:14px;text-align:center}");
            sb.AppendLine(".score-val{font-size:28px;font-weight:700;margin-bottom:4px}");
            sb.AppendLine(".score-lbl{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:.5px}");
            sb.AppendLine(".green{color:#15803D} .amber{color:#B45309} .red{color:#B91C1C} .navy{color:#0B1F45}");
            sb.AppendLine(".section{margin-bottom:20px}");
            sb.AppendLine($"h2{{font-size:14px;color:{tmpl.PrimaryColour};border-bottom:2px solid {tmpl.AccentColour};padding-bottom:5px;margin:0 0 10px}}");
            sb.AppendLine("table{width:100%;border-collapse:collapse;margin-top:6px;font-size:10px}");
            sb.AppendLine("th{background:#0B1F45;color:#fff;padding:6px 8px;text-align:left;font-size:9px;text-transform:uppercase;letter-spacing:.4px}");
            sb.AppendLine("td{padding:5px 8px;border-bottom:1px solid #f1f5f9;vertical-align:top}");
            sb.AppendLine("tr.crit td{background:#FEF2F2} tr.err td{background:#FFFBEB}");
            sb.AppendLine(".badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:9px;font-weight:700}");
            sb.AppendLine(".b-crit{background:#FEF2F2;color:#B91C1C} .b-err{background:#FFFBEB;color:#B45309}");
            sb.AppendLine(".b-warn{background:#FEF9C3;color:#854D0E} .b-pass{background:#F0FDF4;color:#15803D}");
            sb.AppendLine(".print-btn{background:#0B1F45;color:#fff;border:none;padding:10px 24px;border-radius:6px;font-size:13px;font-weight:700;cursor:pointer;margin-bottom:20px}");
            sb.AppendLine(".print-note{background:#E0F2FE;border:1px solid #7DD3FC;padding:10px 14px;border-radius:6px;margin-bottom:16px;font-size:11px}");
            sb.AppendLine("</style></head><body>");

            // Print button and note
            sb.AppendLine("<div class=\"no-print\">");
            sb.AppendLine("<div class=\"print-note\">📄 <strong>Print to PDF:</strong> Click the button below or press <strong>Ctrl + P</strong> → select <em>Save as PDF</em> as the printer. Set margins to <em>Default</em> and enable <em>Background graphics</em> for the branded header.</div>");
            sb.AppendLine("<button class=\"print-btn\" onclick=\"window.print()\">🖨 Print / Save as PDF</button>");
            sb.AppendLine("</div>");

            // Header
            sb.AppendLine("<div class=\"header\">");
            sb.AppendLine($"<div><div class=\"header-title\">VERIFIQ</div><div class=\"header-sub\">{_appName} | {_company}</div></div>");
            sb.AppendLine($"<div class=\"header-meta\">{_session.CountryMode}<br>{_session.StartedAt:dd MMM yyyy HH:mm} UTC<br>Ref: VERIFIQ-{_session.SessionId:N8[..8]}</div>");
            sb.AppendLine("</div>");

            // Score cards
            string Col(double s) => s >= 80 ? "green" : s >= 60 ? "amber" : "red";
            sb.AppendLine("<div class=\"score-grid\">");
            sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val {Col(score)}\">{score:F1}%</div><div class=\"score-lbl\">Data Score</div></div>");
            if (dc != null) sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val {Col(dScore)}\">{dScore:F1}%</div><div class=\"score-lbl\">Design Score</div></div>");
            if (dc != null) sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val {Col(oScore)}\">{oScore:F1}%</div><div class=\"score-lbl\">Overall Score</div></div>");
            sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val navy\">{_session.TotalElements:N0}</div><div class=\"score-lbl\">Elements</div></div>");
            sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val green\">{_session.PassedElements:N0}</div><div class=\"score-lbl\">Compliant</div></div>");
            sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val amber\">{_session.WarningElements:N0}</div><div class=\"score-lbl\">Warnings</div></div>");
            sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val amber\">{_session.ErrorElements:N0}</div><div class=\"score-lbl\">Errors</div></div>");
            sb.AppendLine($"<div class=\"score-card\"><div class=\"score-val red\">{_session.CriticalElements:N0}</div><div class=\"score-lbl\">Critical</div></div>");
            sb.AppendLine("</div>");

            // Score formulas
            sb.AppendLine("<div class=\"section\">");
            sb.AppendLine("<h2>Score Formulas</h2>");
            sb.AppendLine("<table><thead><tr><th>Score</th><th>Formula</th><th>Result</th></tr></thead><tbody>");
            sb.AppendLine($"<tr><td>Data Score</td><td>({_session.PassedElements} ÷ {_session.TotalElements}) × 100</td><td><strong>{score:F1}%</strong></td></tr>");
            if (dc != null)
            {
                sb.AppendLine($"<tr><td>Design Score</td><td>({dc.PassedChecks} ÷ {dc.TotalChecks}) × 100</td><td><strong>{dScore:F1}%</strong></td></tr>");
                sb.AppendLine($"<tr><td>Overall Score</td><td>({score:F1} + {dScore:F1}) ÷ 2</td><td><strong>{oScore:F1}%</strong></td></tr>");
            }
            sb.AppendLine("</tbody></table></div>");

            // Findings table
            sb.AppendLine("<div class=\"section\">");
            sb.AppendLine($"<h2>Data Compliance Findings ({_session.Results.Count:N0} total)</h2>");
            sb.AppendLine("<table><thead><tr><th>Severity</th><th>Check Level</th><th>Element</th><th>Agency</th><th>Issue</th><th>Remediation</th></tr></thead><tbody>");
            var maxF = tmpl.MaxFindings;
            foreach (var r in _session.Results.OrderByDescending(x => x.Severity).Take(maxF))
            {
                var cls   = r.Severity == Severity.Critical ? " class=\"crit\"" : r.Severity == Severity.Error ? " class=\"err\"" : "";
                var badge = r.Severity == Severity.Critical ? "b-crit" : r.Severity == Severity.Error ? "b-err" : r.Severity == Severity.Warning ? "b-warn" : "b-pass";
                sb.AppendLine($"<tr{cls}>");
                sb.AppendLine($"<td><span class=\"badge {badge}\">{r.Severity}</span></td>");
                sb.AppendLine($"<td>{r.CheckLevel}</td>");
                sb.AppendLine($"<td><strong>{System.Net.WebUtility.HtmlEncode(r.ElementName)}</strong><br><small style=\"color:#64748b\">{r.IfcClass}</small></td>");
                sb.AppendLine($"<td>{r.AffectedAgency}</td>");
                sb.AppendLine($"<td>{System.Net.WebUtility.HtmlEncode(r.Message)}</td>");
                sb.AppendLine($"<td style=\"color:#0E7C86;font-size:9px\">{System.Net.WebUtility.HtmlEncode(r.RemediationGuidance)}</td>");
                sb.AppendLine("</tr>");
            }
            if (_session.Results.Count > 500)
                sb.AppendLine($"<tr><td colspan=\"6\" style=\"text-align:center;font-style:italic;color:#64748b\">... {_session.Results.Count - 500:N0} additional findings not shown. Export to Excel or CSV for the full dataset.</td></tr>");
            sb.AppendLine("</tbody></table></div>");

            sb.AppendLine($"<p style=\"margin-top:20px;font-size:9px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:8px\">{tmpl.FooterText}</p>");
            sb.AppendLine("</body></html>");

            // Save as HTML at the PDF path - browser can open it for print-to-PDF.
            // Rename extension to .html so browsers handle it correctly.
            var htmlPath = System.IO.Path.ChangeExtension(path, ".html");
            File.WriteAllText(htmlPath, sb.ToString(), System.Text.Encoding.UTF8);

            // Open in default browser immediately
            try
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName        = htmlPath,
                    UseShellExecute = true
                });
            }
            catch { /* Non-critical - user can open the file manually. */ }

            // Write a minimal redirect stub at the .pdf path for reference
            File.WriteAllText(path,
                $"VERIFIQ PDF Report v1.0\r\n" +
                $"Generated: {_session.StartedAt:dd MMM yyyy HH:mm} UTC\r\n\r\n" +
                $"The printable HTML version has been saved and opened in your browser:\r\n{htmlPath}\r\n\r\n" +
                $"To save as PDF: press Ctrl+P in the browser, select 'Save as PDF'.\r\n" +
                $"Native PDF generation (no browser required) is planned for VERIFIQ v1.1.");
        }, ct);
    }
}
